<?php
/**
 * Implements hook_field_info().
 *
 * Provides the description of the field.
 */
function voer_field_author_field_info() {
  return array(
    // We name our field as the associative name of the array.
    'field_voer_authors' => array(
      'label' => t('VOER Authors'),
      'description' => t('VOER Authors.'),
      'allowed_values_function' => 'voer_field_author_allowed_values',
      'default_widget' => 'options_buttons',
      'default_formatter' => 'list_default',
    ),
  );
}

/**
 * Implements hook_widget_info_alter().
 *
 */
function voer_field_author_field_widget_info_alter(&$info) {
  $widgets = array(
    'options_select' => array('field_voer_authors'),
  );
  foreach ($widgets as $widget => $field_types) {
    $info[$widget]['field types'] = array_merge($info[$widget]['field types'], $field_types);
  }
}

/**
 * Implements hook_options_list()
 *
 */
function voer_field_author_options_list($field, $instance, $entity_type, $entity) {
  module_load_include('inc', 'voer_api');
  $authors = voer_api_get_all_authors();
  $list = array();
  if ($authors->count > 0){
    foreach ($authors->results as $author) {
      $list[$author->id] = $author->fullname;
    }
  }
  return $list;
}

function voer_field_author_allowed_values($field, $instance, $entity_type, $entity, $cacheable = TRUE){
  module_load_include('inc', 'voer_api');
  $authors = voer_api_get_all_authors();
  $list = array();
  if (isset($authors)){
    foreach ($authors as $author) {
      $list[$author->id] = $author->fullname;
    }
  }
  return $list;
}

/**
 * Implements hook_field_is_empty().
 *
 * hook_field_is_emtpy() is where Drupal asks us if this field is empty.
 * Return TRUE if it does not contain data, FALSE if it does. This lets
 * the form API flag an error when required fields are empty.
 */
function voer_field_author_field_is_empty($item, $field) {
  return empty($item['value']);
}
