<?php

define('VOER_COLLECTION_UI', 'voer_collection_ui');

/**
 * Implements hook_theme().
 */
function voer_collection_ui_theme(&$existing) {
  $themes = array(
    'node__collection__type' => array(
      'path' => drupal_get_path('module', 'VOER_COLLECTION_UI') . '/theme',
      'render element' => 'elements',
      'template' => 'node--collection--type',
    ),
    'node__collection__type__collection__list' => array(
      'path' => drupal_get_path('module', 'VOER_COLLECTION_UI') . '/theme',
      'render element' => 'elements',
      'template' => 'node--collection--type--collection--list',
    ),
    'commerce_product__product_in_cart' => array(
      'path' => drupal_get_path('module', 'VOER_COLLECTION_UI') . '/theme',
      'render element' => 'elements',
      'template' => 'commerce_product__product_in_cart',
    ),
  );
  return $themes;
}

function voer_collection_ui_block_info(){
  $blocks['voer_collection_outline_block'] = array(
    'info' => t('VOER Collection Outline'),
  );
  return $blocks;
}

function voer_collection_ui_block_view($delta=''){
  $block = array();

  switch($delta) {
    case 'voer_collection_outline_block' :
      $block['content'] = voer_collection_outline_block_view();
      break;
  }

  return $block;
}

function voer_collection_outline_block_view(){
  $current_path = isset($_GET['q']) ? $_GET['q'] : "";
  $params = explode("/", $current_path);
  if ($params[0] == "node" || $params[0] == "collection"){
    if (isset($params[1])){
      $node = node_load($params[1]);
      if ($node->type == "voer_collection"){
        $outline = $node->field_voer_outline[$node->language][0]['value'];
        $outline = json_decode($outline);
        if ($outline){
          $items = _walk_through($outline, $node->nid);
          return theme('item_list', array("items" => $items, 'attributes' => array('class' => 'nav nav-list')));
        }
      }
    }
  }
  return "";
}

function _walk_through($arrItems, $nid = 0){
  $result = array();
  if ($item->type == "module"){
    $id = $item->id;
    $pies = explode("|", $id);
    $module_id = $pies[0];
    $a['data'] = l($item->title, 'collection/' . $nid . "/" .$module_id);
  }else if ($item->type == 'subcollection'){
    foreach ($item->content as $m){
      $r = _walk_through($m, $nid);
      $result[] = $r;
    }
  }
  foreach ($arrItems as $item){
    $item = (array) $item;
    $a = array();
    if (array_key_exists("children", $item)){
      $a['children'] = _walk_through($item['children'], $nid);
    }
    if ($item['attr']->rel == 'module'){
    }else{
      if (array_key_exists("children", $a)){
        $a['data'] = l($item['data'], 'm/#');
      }else{
        $a['data'] = l($item['data'], '#');
      }
    }
    $result[] = $a;
  }
  return $result;
}

