<?php

define('VOER_COLLECTION_UI', 'voer_collection_ui');

/**
 * Implements hook_theme().
 */
function voer_collection_ui_theme(&$existing) {
  $themes = array(
    'node__collection__type' => array(
      'path' => drupal_get_path('module', 'VOER_COLLECTION_UI') . '/theme',
      'render element' => 'elements',
      'template' => 'node--collection--type',
    ),
    'node__collection__type__collection__list' => array(
      'path' => drupal_get_path('module', 'VOER_COLLECTION_UI') . '/theme',
      'render element' => 'elements',
      'template' => 'node--collection--type--collection--list',
    ),
    'commerce_product__product_in_cart' => array(
      'path' => drupal_get_path('module', 'VOER_COLLECTION_UI') . '/theme',
      'render element' => 'elements',
      'template' => 'commerce_product__product_in_cart',
    ),
  );
  return $themes;
}


