<?php

/**
 * Implements hook_block_info().
 * @return [type] [description]
 */
function voer_blocks_block_info(){
  // This example comes from node.module.
  $blocks['voer_categories_block'] = array(
    'info' => t('VOER - Categories'),
  );

  $blocks['voer_modules_block'] = array(
    'info' => t('VOER - Modules'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function voer_blocks_block_view($delta='') {
  $block = array();

  switch($delta) {
    case 'voer_categories_block' :
      $block['content'] = voer_categories_block_view();
      break;
    case 'voer_modules_block' :
      $block['content'] = voer_modules_block_view();
      break;
  }

  return $block;
}

function voer_categories_block_view(){
  $output = array();

  module_load_include('inc', 'voer_api');
  try {
    $categories = voer_api_get_all_categories();
    $list = array();
    if (isset($categories) && isset($categories->results)){
      foreach ($categories->results as $category) {
        $list[$category->id] = l($category->name, 'category/' . $category->id, array('class' => 'category-link'));
      }
    }

    // Block output in HTML with div wrapper
    $output[] = array(
      '#theme' => 'item_list',
      '#items' => $list,
      '#attributes' => array('class' => 'category_list span6'),
    );

    return $output;
  } catch (Exception $e) {
    return "";
  }
}

function voer_modules_block_view()
{
  //Fix module_id
  $module_id = 'd6b8604a485be63dcecc358789dfbaef';

  module_load_include('inc', 'voer_api');
  try {
    $module_list = voer_api_get_all_materials();

    $module = (array)voer_api_get_detail_material($module_id);
    $module['content_type'] = 'module';
    $module['total_count'] = $module_list->count;

    $category = (array)voer_api_get_category($module['categories']);

    if ($category) {
      $module['category_name'] = $category['name'];
    }

    return theme('voer_module_custom', $module);

  } catch (Exception $e) {
    return "";
  }
}

/**
* Implemtnation of hook_theme()
*/
function voer_blocks_theme($existing, $type, $theme, $path) {
  return array(
    'voer_module_custom' => array(
      'arguments' => array('module' => array()),
      'template' => 'templates/block--voer-module',
    ),
  );
}
