<?php

/**
 * Implements hook_block_info().
 * @return [type] [description]
 */
function voer_blocks_block_info(){
  // This example comes from node.module.
  $blocks['voer_categories_block'] = array(
    'info' => t('VOER - Categories'),
  );

  $blocks['voer_modules_block'] = array(
    'info' => t('VOER - Featured modules'),
  );

  $blocks['voer_collections_block'] = array(
    'info' => t('VOER - Featured collections'),
  );

  $blocks['voer_courses_block'] = array(
    'info' => t('VOER - Featured courses'),
  );

  $blocks['voer_questionaire_block'] = array(
    'info' => t('VOER - Questionnaire'),
  );

  $blocks['voer_help_support_block'] = array(
    'info' => t('VOER - Help & Support'),
  );

  $blocks['voer_featured_author_block'] = array(
    'info' => t('VOER - Featured authors'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function voer_blocks_block_view($delta='') {
  $block = array();

  switch($delta) {
    case 'voer_categories_block' :
      $block['content'] = voer_categories_block_view();
      break;
    case 'voer_modules_block' :
      $block['content'] = voer_modules_block_view();
      break;
    case 'voer_collections_block' :
      $block['content'] = voer_collections_block_view();
      break;
    case 'voer_courses_block' :
      $block['content'] = voer_courses_block_view();
      break;
    case 'voer_questionaire_block' :
      $block['content'] = voer_questionaires_block_view();
      break;
    case 'voer_help_support_block' :
      $block['content'] = voer_help_supports_block_view();
      break;
    case 'voer_featured_author_block' :
      $block['content'] = voer_featured_authors_block_view();
      break;
  }

  return $block;
}

function voer_categories_block_view(){
  $output = array();

  module_load_include('inc', 'voer_api');
  try {
    $categories = voer_api_get_all_categories();
    // dpm($categories);
    $list = array();
    if (isset($categories)){
      foreach ($categories as $category) {
        //Chi lay nhung category co so bai viet > 0
        $catinfo = voer_api_get_materials_by_categories(array($category->id));
        $total = $catinfo->count;
        if ($total > 0){
          $list[$category->id] = l($category->name . " ($total)", 'category/' . $category->id, array('class' => 'category-link'));
        }
      }
    }

    // Block output in HTML with div wrapper
    $output[] = array(
      '#theme' => 'item_list',
      '#items' => $list,
      '#attributes' => array('class' => 'category_list span6'),
    );

    return $output;
  } catch (Exception $e) {
    return "";
  }
}

function voer_modules_block_view()
{
  //Fix module_id
  $module_id = 'c8095bba9ac9e9a5c317e978a6bbf83b';

  module_load_include('inc', 'voer_api');
  try {
    $module_list = voer_api_get_all_materials();

    $module = (array)voer_api_get_detail_material($module_id);
    $module['content_type'] = 'module';
    $module['total_count'] = $module_list->count;
    $module['image_path'] = drupal_get_path('module', 'voer_blocks') . '/images/default_module_image.jpg';

    $category = (array)voer_api_get_category($module['categories']);

    if ($category) {
      $module['category_name'] = $category['name'];
    }

    return theme('voer_module_custom', $module);

  } catch (Exception $e) {
    return "";
  }
}

function voer_collections_block_view()
{
  //Fix module_id
  $module_id = '4d8788745d285b27e59b74abdc95c16c';

  module_load_include('inc', 'voer_api');
  try {
    $module_list = voer_api_get_all_materials();

    $module = (array)voer_api_get_detail_material($module_id);
    $module['content_type'] = 'collection';
    $module['total_count'] = $module_list->count;
    $module['image_path'] = drupal_get_path('module', 'voer_blocks') . '/images/default_collection_image.jpg';

    $category = (array)voer_api_get_category($module['categories']);

    if ($category) {
      $module['category_name'] = $category['name'];
    }

    return theme('voer_module_custom', $module);

  } catch (Exception $e) {
    return "";
  }
}

function voer_questionaires_block_view()
{
  //Fix module_id
  $module_id = 'e01b8a3751d7bd0a35e0a49acae2c553';

  module_load_include('inc', 'voer_api');
  try {
    $module_list = voer_api_get_all_materials();

    $module = (array)voer_api_get_detail_material($module_id);
    $module['content_type'] = 'questionaire';
    $module['total_count'] = $module_list->count;
    $module['image_path'] = drupal_get_path('module', 'voer_blocks') . '/images/default_questionaire_image.jpg';

    $category = (array)voer_api_get_category($module['categories']);

    if ($category) {
      $module['category_name'] = $category['name'];
    }

    return theme('voer_module_custom', $module);

  } catch (Exception $e) {
    return "";
  }
}

function voer_help_supports_block_view()
{
  //Fix module_id
  $module_id = '69438c8cacae020980771950fd845977';

  module_load_include('inc', 'voer_api');
  try {
    $module_list = voer_api_get_all_materials();

    $module = (array)voer_api_get_detail_material($module_id);
    $module['content_type'] = 'help & support';
    $module['total_count'] = $module_list->count;
    $module['image_path'] = drupal_get_path('module', 'voer_blocks') . '/images/default_help_support_image.jpg';

    $category = (array)voer_api_get_category($module['categories']);

    if ($category) {
      $module['category_name'] = $category['name'];
    }

    return theme('voer_module_custom', $module);

  } catch (Exception $e) {
    return "";
  }
}

function voer_courses_block_view()
{
  //Fix module_id
  $module_id = '0129752be25c3bb959674c321829464a';

  module_load_include('inc', 'voer_api');
  try {
    $module_list = voer_api_get_all_materials();

    $module = (array)voer_api_get_detail_material($module_id);
    $module['content_type'] = 'courseware';
    $module['total_count'] = $module_list->count;
    $module['image_path'] = drupal_get_path('module', 'voer_blocks') . '/images/default_courseware_image.jpg';

    $category = (array)voer_api_get_category($module['categories']);

    if ($category) {
      $module['category_name'] = $category['name'];
    }

    return theme('voer_module_custom', $module);

  } catch (Exception $e) {
    return "";
  }
}

function voer_featured_authors_block_view()
{
  module_load_include('inc', 'voer_api');
  $author_list = (array)voer_api_get_all_authors();

  if (!isset($author_list['detail'])) {
    $author = array();
    $author['sub_title'] = t('featured authors');
    $author['total_count'] = $author_list['count'];

    $max_range = 9;

    if ($author_list['count'] - 1 < 9) {
      $max_range = $author_list['count'] - 1;
    }

    $randomAuthor = rand(0, $max_range);
    foreach ($author_list['results'][$randomAuthor] as $key => $value) {
      if ($key == 'id') {
        $key = 'author_id';
      }
      $author[$key] = $value;
    }

    // $author['person_id'] = $author['id'];

    return theme('voer_module_featured_author', $author);

  } else {
    return "";
  }
}

/**
* Implemtnation of hook_theme()
*/
function voer_blocks_theme($existing, $type, $theme, $path) {
  return array(
    'voer_module_custom' => array(
      'arguments' => array('module' => array()),
      'template' => 'templates/block--voer-module',
    ),
    'voer_module_featured_author' => array(
      'arguments' => array('author' => array()),
      'render element' => 'element',
      'template' => 'templates/block--voer-featured-author--view',
    ),
  );
}
