<?php

function voer_module_ui_theme(&$existing) {
  $themes = array(
    'node__voer__module' => array(
      'path' => drupal_get_path('module', 'voer_module_ui') . '/theme',
      'render element' => 'elements',
      'template' => 'node--voer-module',
    ),
  );
  return $themes;
}

/**
 * Override or insert variables into the node template.
 */
function voer_module_ui_preprocess_node(&$vars) {
  // drupal_set_message(t('DEBUG: <pre>@vars<pre>', array('@vars' => print_r($vars, true))));
  if (isset($vars['type']) && $vars['type'] == 'voer_module') {
    $vars['theme_hook_suggestions'][] = 'node__voer__module';
    $vars['classes_array'][] = 'node-voer-module';
  }
}
