<?php
	/*
	 * -  Function get a content from respository
	 * -  Function commit a content version to respository
	 * -  Function search in respository
	 */

//define('VOER_API_VERSION', '3');

/**
 * Implementation of hook_menu().
 */
function voer_api_menu() {
  $items['admin/config/services/voer'] = array(
    'title' => 'VOER',
    'description' => 'Configure VOER settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('voer_admin_settings'),
    'file' => 'voer_settings_ui.inc',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['voer/test'] = array(
    'title' => 'VOER Test',
    'page callback' => '_voer_api_test',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );

  return $items;
}

function _voer_api_test(){
  module_load_include('inc', 'voer_api');

  //get all category
  // voer_api_refresh_token();
  // $categories = voer_api_get_all_materials();
  // print_r($categories);
  // dpm($categories);

  // $category = voer_api_get_category(2);
  // dpm($category);

  //insert category
  // $category = (object) array('id' => 1, 'name' => 'Category 999', 'parent' => '0', 'description' => 'Description of category 1');
  //$result = voer_api_create_category($category);
  // $result = voer_api_update_category($category);
  //
  // $result = voer_api_authenticate();
  // dpm($result);
  //$modules = voer_api_get_modules();
  //dpm($modules);

  //get all authors
  //$authors = voer_api_get_all_authors();
  //dpm($authors);

  //TEST for TRANSFORMER
  $file = "@" . realpath("./test1.docx") . ";filename=test1.docx";
  //print $file;
  // voer_api_refresh_token();
  $result = voer_api_import($file);

  print $result;

  return "";
}
