<?php

function voer_module_ui_menu(){
  // The page to view our entities - needs to follow what
  // is defined in basic_uri and will use load_basic to retrieve
  // the necessary entity info.
  $items['module/%voer_module'] = array(
    // 'title callback' => 'voer_module_title',
    // 'title arguments' => array(1),
    'page callback' => 'node_view',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * [voer_content_title description]
 * @param  [type] $content [description]
 * @return [type]          [description]
 */
function voer_module_title($module){
  return $module->title;
}

// TODO:
function voer_module_view($module){
  $m = $module;
  $node = new stdClass();
  $node->type = 'voer_module';
  node_object_prepare($node);
  $node->title = $m->title;
  $node->language = LANGUAGE_NONE;
  $node->body[$node->language][0]['value'] = $m->text;
  $node->body[$node->language][0]['format']  = 'full_html';
  $node->field_voer_description[$node->language][0]['value'] = $m->description;
  $node = (array) $node;
  return theme("voer_module_detail", $node);
}

/**
 * Load a module with material_id
 * @param  [type]  $id    [description]
 * @param  boolean $reset [description]
 * @return [type]         [description]
 */
function voer_module_load($id = NULL, $reset = FALSE){
  module_load_include('inc', 'voer_content');
  $node = voer_material_load($id);
  if ($node){
    drupal_goto("node/" . $node->nid);
    return FALSE;
  }else{
    return FALSE;
  }
}

function voer_module_ui_theme(&$existing) {
  $themes = array(
    'voer_module_detail' => array(
      'path' => drupal_get_path('module', 'voer_module_ui') . '/theme',
      // 'variables' => array("module" => NULL),
      'render element' => 'element',
      'template' => 'voer-module-detail',
    ),
  );
  return $themes;
}


