<?php

function voer_module_ui_menu(){
  // The page to view our entities - needs to follow what
  // is defined in basic_uri and will use load_basic to retrieve
  // the necessary entity info.
  $items['module/%voer_module'] = array(
    'title callback' => 'voer_module_title',
    'title arguments' => array(1),
    'page callback' => 'node_view',
    'page arguments' => array(1),
    'access arguments' => array('view any module'),
  );

  return $items;
}

/**
 * [voer_content_title description]
 * @param  [type] $content [description]
 * @return [type]          [description]
 */
function voer_module_title($module){
  return $module->title;
}

// TODO:
function voer_module_view($module){
  $m = $module;
  $node = new stdClass();
  $node->type = 'voer_module';
  node_object_prepare($node);
  $node->title = $m->title;
  $node->language = LANGUAGE_NONE;
  $node->body[$node->language][0]['value'] = $m->text;
  $node->body[$node->language][0]['format']  = 'full_html';
  $node->field_voer_description[$node->language][0]['value'] = $m->description;
  $node = (array) $node;
  return theme("voer_module_detail", $node);
}

/**
 * Load a module with material_id
 * @param  [type]  $id    [description]
 * @param  boolean $reset [description]
 * @return [type]         [description]
 */
function voer_module_load($id = NULL, $reset = FALSE){
  $material_id = $id;
  $version = 1;
  module_load_include('inc', 'voer_api');
  try {
    $m = voer_api_get_detail_material($id);

    $node = new stdClass();
    $node->type = 'voer_module';
    node_object_prepare($node);
    $node->title = $m->title;
    $node->language = LANGUAGE_NONE;
    $node->body[$node->language][0]['value'] = $m->text;
    $node->body[$node->language][0]['format']  = 'full_html';
    // $node->field_voer_description[$node->language][0]['value'] = $m->description;
    // $node->field_voer_categories[$node->language][0]['value'] = $m->categories;
    // $node->field_voer_language[$node->language][0]['value'] = $m->language;

    $node->nid = 0;
    return $node;
  } catch (Exception $e) {
    drupal_set_message(t("There are network problems!. ") . $e->getMessage());
    return FALSE;
  }
}

function voer_module_ui_theme(&$existing) {
  $themes = array(
    'voer_module_detail' => array(
      'path' => drupal_get_path('module', 'voer_module_ui') . '/theme',
      // 'variables' => array("module" => NULL),
      'render element' => 'element',
      'template' => 'voer-module-detail',
    ),
  );
  return $themes;
}


