<?php

function voer_module_ui_menu(){
  // The page to view our entities - needs to follow what
  // is defined in basic_uri and will use load_basic to retrieve
  // the necessary entity info.
  $items['m/%voer_module'] = array(
    // 'title callback' => 'voer_module_title',
    // 'title arguments' => array(1),
    'page callback' => 'node_view',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );

  $items['m/all'] = array(
    'title' => t('List modules'),
    'page callback' => 'show_material_list_page',
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * [voer_content_title description]
 * @param  [type] $content [description]
 * @return [type]          [description]
 */
function voer_module_title($module){
  return $module->title;
}

// TODO:
function voer_module_view($module){
  $m = $module;
  $node = new stdClass();
  $node->type = 'voer_module';
  node_object_prepare($node);
  $node->title = $m->title;
  $node->language = LANGUAGE_NONE;
  $node->body[$node->language][0]['value'] = $m->text;
  $node->body[$node->language][0]['format']  = 'full_html';
  $node->field_voer_description[$node->language][0]['value'] = $m->description;
  $node = (array) $node;
  return theme("voer_module_detail", $node);
}

/**
 * Load a module with material_id
 * @param  [type]  $id    [description]
 * @param  boolean $reset [description]
 * @return [type]         [description]
 */
function voer_module_load($id = NULL, $reset = FALSE){
  module_load_include('inc', 'voer_content');
  $node = voer_material_load($id);
  if ($node){
    if ($node->type == "voer_module"){
      drupal_goto("node/" . $node->nid);
    }else if ($node->type == "voer_collection"){
      drupal_goto("collection/" . $node->nid);
    }
    return FALSE;
  }else{
    return FALSE;
  }
}

function voer_module_ui_theme(&$existing) {
  $themes = array(
    'voer_module_detail' => array(
      'path' => drupal_get_path('module', 'voer_module_ui') . '/theme',
      // 'variables' => array("module" => NULL),
      'render element' => 'element',
      'template' => 'voer-module-detail',
    ),
  );
  return $themes;
}

function show_material_list_page() {
  module_load_include('inc', 'voer_api');
  try {
    $page = isset($_GET['page']) ? $_GET['page'] : 0;
    $materials = voer_api_get_all_materials(VOER_MATERIAL_TYPE_MODULE, $page + 1);
    if ($materials->count == 0){
      return t("Materials not found!");
    }else{
      $nodes = array();
      pager_default_initialize($materials->count, 10);
      foreach ($materials->results as $key => $material) {
        $node = new stdClass();
        $node->type = 'voer_module';
        node_object_prepare($node);
        $node->title = $material->title;
        $node->material_id = $material->material_id;
        $node->nid = $key;
        $node->comment = 0;
        $node->field_voer_description[LANGUAGE_NONE][0]['value'] = $material->description;
        $nodes[] = $node;
      }
      $output = node_view_multiple($nodes);
      $output['pager'] = array('#markup' => theme('pager'));
      return $output;
    }
  } catch (Exception $e) {
    drupal_set_message($e->getMessage(), 'error');
    return "";
  }
}
