<?php

function voer_person_menu(){
  $items = array();
  $items['person/%person'] = array(
    'page callback' => 'show_person_page',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );

  $items['person/search'] = array(
    'page callback' => 'search_person_by_keyword',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['person/info'] = array(
    'page callback' => 'load_person_info',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function voer_person_theme(){
  return array(
    'voer_person_view' => array(
      'arguments' => array('person' => array()),
      'render element' => 'element',
      'template' => 'templates/voer-person-view',
    ),
  );
}

function person_load($id = NULL){
  module_load_include('inc', 'voer_api');
  $person = voer_api_get_author($id);
  if ($person){
    return $person;
  }else{
    return FALSE;
  }
}

function show_person_page($person){

  return theme("voer_person_view", (array) $person) . drupal_render(show_materials_by_authors($person));
}

function show_materials_by_authors($person){
  module_load_include('inc', 'voer_api');
  try {
    $page = isset($_GET['page']) ? $_GET['page'] : 0;
    $materials = voer_api_get_materials_by_authors(array($person->id), $page + 1);
    if ($materials->count == 0){
      return t("Materials not found!");
    }else{
      $nodes = array();
      pager_default_initialize($materials->count, 10);
      foreach ($materials->results as $key => $material) {
        $node = new stdClass();
        $node->type = 'voer_module';
        node_object_prepare($node);
        $node->title = $material->title;
        $node->material_id = $material->material_id;
        $node->nid = $key;
        $node->comment = 0;
        $node->field_voer_description[LANGUAGE_NONE][0]['value'] = $material->description;
        $nodes[] = $node;
      }
      $output = node_view_multiple($nodes);
      $output['pager'] = array('#markup' => theme('pager'));
      return $output;
    }
  } catch (Exception $e) {
    drupal_set_message($e->getMessage(), 'error');
    return "";
  }
}

function search_person_by_keyword()
{
  $keyword = $_POST['keyword'];
  $page = isset($_POST['page']) ? $_POST['page'] : 1;
  $author_selected_list = isset($_POST['author_list']) ? $_POST['author_list'] : 1;

  $author_selected_array = explode(',', $author_selected_list);

  module_load_include('inc', 'voer_api');
  $authors = voer_api_search_on_person($keyword, $page);

  $author_list = array();

  if ($authors->count > 0) {
    foreach ($authors->results as $author) {
      $author_list[$author->id] = $author->fullname;
    }

    $row_data = array();
    foreach ($author_list as $id => $fullname) {
      $row_data_tmp = array();
      $row_data_tmp[] = array(
        'data' => theme('html_tag', array('element' => array(
          '#type' => 'html_tag',
          '#tag' => 'span',
          '#value' => $fullname,
        ))),
      );

      if (in_array($id, $author_selected_array)) {
        $class_name = 'display_none';
      } else {
        $class_name = '';
      }

      $row_data_tmp[] = array(
        'data' => theme('html_tag', array('element' => array(
          '#type' => 'html_tag',
          '#tag' => 'div',
          '#attributes' => array(
            'class' => array($class_name),
          ),
          '#value' => '<span class="voer-add-authors" rel="'.$id.'"></span>'
        ))),
        'class' => 'voer-add-authors-'.$id,
      );

      $row_data[] = $row_data_tmp;
    }

    $header = array(t('Name'), t('Add'));
    $table_attributes = array('id' => 'voer-author-table-list', 'align' => 'center');
    $author_table_list = theme('table', array('header' => $header, 'rows' => $row_data, 'attributes' => $table_attributes, 'sticky' => FALSE, 'empty' => t('No data.')));

    $next_button = array();
    $prev_button = array();

    if ($authors->next) {
      $next_button = array(
        '#type' => 'button',
        '#value' => 'Next',
        '#attributes' => array(
          'class' => array('author_next_btn'),
          'page' => $page + 1,
          'keyword' => check_plain($keyword),
          'onclick' => 'loadAuthorSearchPage(this)',
        ),
      );
    }

    if ($authors->previous) {
      $prev_button = array(
        '#type' => 'button',
        '#value' => 'Prev',
        '#attributes' => array(
          'class' => array('author_prev_btn'),
          'page' => $page - 1,
          'keyword' => check_plain($keyword),
          'onclick' => 'loadAuthorSearchPage(this)',
        ),
      );
    }

    echo $author_table_list . drupal_render($prev_button) . drupal_render($next_button);

  } else {
    echo t('No result');
  }
}

function load_person_info()
{
  $author_id = $_GET['author_id'];
  module_load_include('inc', 'voer_api');
  $author = (array)voer_api_get_author($author_id);
  if (!isset($author['detail'])) {
    echo drupal_json_encode($author);
  }
  echo '';
}